// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import {
  MultiBetRequestSpecialBetRequest,
  MultiBetResponseSpecialBetResponse,
  PlaceBetRequest,
  PlaceParlayBetRequest,
  PlaceParlayBetResponse,
  PlaceStraightBetResponse,
  PlaceTeaserBetRequest,
  PlaceTeaserBetResponse,
  multiBetRequestSpecialBetRequestRequest,
  multiBetResponseSpecialBetResponseResponse,
  placeBetRequestRequest,
  placeParlayBetRequestRequest,
  placeParlayBetResponseResponse,
  placeStraightBetResponseResponse,
  placeTeaserBetRequestRequest,
  placeTeaserBetResponseResponse,
} from './models';

export class PlaceBetsService extends BaseService {
  /**
 * Place straight bet (SPREAD, MONEYLINE, TOTAL_POINTS, TEAM_TOTAL_POINTS).
Please note when the status is PENDING_ACCEPTANCE and if the live delay was applied, the response will not have betId. Client would have to call /bets by uniqueRequestId to check the status if the bet was ACCEPTED.  For more details please see [How to place a bet on live events?](https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/FAQ.md#how-to-place-a-bet-on-live-events)

Make sure you handle properly the case of an unexpected error as per
 [How to handle error on placing a bet?](https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/FAQ.md#how-to-handle-unexpected-error-on-placing-a-bet)

 * @returns {Promise<HttpResponse<PlaceStraightBetResponse>>} OK
 */
  async betsStraightV2(
    body: PlaceBetRequest,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<PlaceStraightBetResponse>> {
    const path = '/v4/bets/straight';
    const options: any = {
      responseSchema: placeStraightBetResponseResponse,
      requestSchema: placeBetRequestRequest,
      body: body as any,
      headers: {
        'Content-Type': 'application/json',
      },
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.post(path, options);
  }

  /**
 * Make sure you handle properly the case of an unexpected error as per
 [How to handle error on placing a bet?](https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/FAQ.md#how-to-handle-unexpected-error-on-placing-a-bet)

 * @returns {Promise<HttpResponse<PlaceParlayBetResponse>>} OK
 */
  async betsParlayV2(
    body: PlaceParlayBetRequest,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<PlaceParlayBetResponse>> {
    const path = '/v4/bets/parlay';
    const options: any = {
      responseSchema: placeParlayBetResponseResponse,
      requestSchema: placeParlayBetRequestRequest,
      body: body as any,
      headers: {
        'Content-Type': 'application/json',
      },
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.post(path, options);
  }

  /**
 * Make sure you handle properly the case of an unexpected error as per
 [How to handle error on placing a bet?](https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/FAQ.md#how-to-handle-unexpected-error-on-placing-a-bet)

 * @returns {Promise<HttpResponse<PlaceTeaserBetResponse>>} OK
 */
  async betsTeaser(
    body: PlaceTeaserBetRequest,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<PlaceTeaserBetResponse>> {
    const path = '/v4/bets/teaser';
    const options: any = {
      responseSchema: placeTeaserBetResponseResponse,
      requestSchema: placeTeaserBetRequestRequest,
      body: body as any,
      headers: {
        'Content-Type': 'application/json',
      },
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.post(path, options);
  }

  /**
 * Make sure you handle properly the case of an unexpected error as per
 [How to handle error on placing a bet?](https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/FAQ.md#how-to-handle-unexpected-error-on-placing-a-bet)

 * @returns {Promise<HttpResponse<MultiBetResponseSpecialBetResponse>>} OK
 */
  async betsSpecial(
    body: MultiBetRequestSpecialBetRequest,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<MultiBetResponseSpecialBetResponse>> {
    const path = '/v4/bets/special';
    const options: any = {
      responseSchema: multiBetResponseSpecialBetResponseResponse,
      requestSchema: multiBetRequestSpecialBetRequestRequest,
      body: body as any,
      headers: {
        'Content-Type': 'application/json',
      },
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.post(path, options);
  }
}
