// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const fillType = z.enum(['NORMAL', 'FILLANDKILL', 'FILLMAXLIMIT']);

export type FillType = z.infer<typeof fillType>;
