// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const parlayLegRequestSide = z.enum(['OVER', 'UNDER']);

export type ParlayLegRequestSide = z.infer<typeof parlayLegRequestSide>;
