// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const placeStraightBetResponseStatus = z.enum(['ACCEPTED', 'PENDING_ACCEPTANCE', 'PROCESSED_WITH_ERROR']);

export type PlaceStraightBetResponseStatus = z.infer<typeof placeStraightBetResponseStatus>;
