import { z } from 'zod';

export const placeParlayBetResponseErrorCode = z.enum([
  'ABOVE_MAX_BET_AMOUNT',
  'ALL_BETTING_CLOSED',
  'BELOW_MIN_BET_AMOUNT',
  'BLOCKED_BETTING',
  'BLOCKED_CLIENT',
  'INSUFFICIENT_FUNDS',
  'INVALID_COUNTRY',
  'INVALID_LEGS',
  'INVALID_ODDS_FORMAT',
  'INVALID_ROUND_ROBIN_OPTIONS',
  'ROUND_ROBIN_DISALLOWED',
  'TOO_MANY_LEGS',
  'TOO_FEW_LEGS',
  'RESPONSIBLE_BETTING_RISK_LIMIT_EXCEEDED',
  'RESPONSIBLE_BETTING_LOSS_LIMIT_EXCEEDED',
  'INVALID_REQUEST',
  'DUPLICATED_REQUEST',
  'SYSTEM_ERROR_3',
]);

export type PlaceParlayBetResponseErrorCode = z.infer<typeof placeParlayBetResponseErrorCode>;
