import { z } from 'zod';

export const placeStraightBetResponseErrorCode = z.enum([
  'ALL_BETTING_CLOSED',
  'ALL_LIVE_BETTING_CLOSED',
  'ABOVE_EVENT_MAX',
  'ABOVE_MAX_BET_AMOUNT',
  'BELOW_MIN_BET_AMOUNT',
  'BLOCKED_BETTING',
  'BLOCKED_CLIENT',
  'INSUFFICIENT_FUNDS',
  'INVALID_COUNTRY',
  'INVALID_EVENT',
  'INVALID_ODDS_FORMAT',
  'LINE_CHANGED',
  'LISTED_PITCHERS_SELECTION_ERROR',
  'OFFLINE_EVENT',
  'PAST_CUTOFFTIME',
  'RED_CARDS_CHANGED',
  'SCORE_CHANGED',
  'TIME_RESTRICTION',
  'DUPLICATED_REQUEST',
  'INCOMPLETE_CUSTOMER_BETTING_PROFILE',
  'INVALID_CUSTOMER_PROFILE',
  'LIMITS_CONFIGURATION_ISSUE',
  'RESPONSIBLE_BETTING_LOSS_LIMIT_EXCEEDED',
  'RESPONSIBLE_BETTING_RISK_LIMIT_EXCEEDED',
  'SYSTEM_ERROR_3',
  'LICENCE_RESTRICTION_LIVE_BETTING_BLOCKED',
  'BETTING_SUSPENDED',
]);

export type PlaceStraightBetResponseErrorCode = z.infer<typeof placeStraightBetResponseErrorCode>;
