// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const teaserBetLegSide = z.enum(['OVER', 'UNDER']);

export type TeaserBetLegSide = z.infer<typeof teaserBetLegSide>;
