// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { BettingStatusResponse, bettingStatusResponseResponse } from './models';

export class BettingStatusService extends BaseService {
  /**
   * Returns current betting status. During maintenance windows betting could be disabled, you can call this operation to check the current betting status.
   * @returns {Promise<HttpResponse<BettingStatusResponse>>} OK
   */
  async betsGetBettingStatus(requestConfig?: RequestConfig): Promise<HttpResponse<BettingStatusResponse>> {
    const path = '/v4/bets/betting-status';
    const options: any = {
      responseSchema: bettingStatusResponseResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }
}
