// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const parlayLegSide = z.enum(['OVER', 'UNDER']);

export type ParlayLegSide = z.infer<typeof parlayLegSide>;
