// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const teaserLegSide = z.enum(['OVER', 'UNDER']);

export type TeaserLegSide = z.infer<typeof teaserLegSide>;
